import { buildMimeMessage, createMultiRecipientGmailDraft, deleteGmailDraft } from './draft-service.js';
import { getCachedProfile } from '../profile/profile-loader.js';

console.log('=== Test 1: Testing RFC 2822 MIME Builder Unit Logic ===');

const profile = getCachedProfile();
const mockResumePdf = Buffer.from('%PDF-1.4 Mock Resume PDF Content');
const mockCoverLetterPdf = Buffer.from('%PDF-1.4 Mock Cover Letter PDF Content');

const mimeResult = buildMimeMessage({
  toEmails: ['recruiter1@company.ae', 'recruiter2@company.ae'],
  subject: `Software Engineer Application - ${profile.name}`,
  bodyText: `Hi Team,\n\nPlease find attached my tailored Resume and Cover Letter for your review.\n\nBest regards,\n${profile.name}`,
  resumePdfBuffer: mockResumePdf,
  resumeFileName: 'Candidate_CV_Careem_Frontend.pdf',
  coverLetterPdfBuffer: mockCoverLetterPdf,
  coverLetterFileName: 'Candidate_CoverLetter_Careem_Frontend.pdf',
});

console.log('• Raw MIME length:', mimeResult.rawMime.length, 'chars');
console.log('• Base64Url length:', mimeResult.base64Url.length, 'chars');

if (!mimeResult.rawMime.includes('To: recruiter1@company.ae, recruiter2@company.ae')) {
  console.error('❌ Multi-recipient To header missing from MIME');
  process.exit(1);
}

if (!mimeResult.rawMime.includes('Candidate_CV_Careem_Frontend.pdf')) {
  console.error('❌ Resume attachment filename missing from MIME');
  process.exit(1);
}

if (!mimeResult.rawMime.includes('Candidate_CoverLetter_Careem_Frontend.pdf')) {
  console.error('❌ Cover Letter attachment filename missing from MIME');
  process.exit(1);
}

console.log('✅ RFC 2822 MIME message construction verified!');

console.log('\n=== Test 2: Testing Live Gmail API Draft Creation ===');

try {
  console.log('• Connecting to Gmail API...');
  const draft = await createMultiRecipientGmailDraft({
    toEmails: ['recruiter.test@company.com'],
    subject: `🧪 [PULSEREACH TEST DRAFT] Frontend Engineer Application - ${profile.name}`,
    bodyText: 'This is an automated test draft generated by Pulsereach verification.',
    resumePdfBuffer: mockResumePdf,
    resumeFileName: 'Candidate_CV_Test.pdf',
    coverLetterPdfBuffer: mockCoverLetterPdf,
    coverLetterFileName: 'Candidate_CoverLetter_Test.pdf',
  });

  console.log(`✅ Live Gmail Draft Created Successfully!`);
  console.log(`• Draft ID: ${draft.draftId}`);
  console.log(`• Message ID: ${draft.messageId}`);

  console.log('\n• Cleaning up test draft via Gmail API...');
  await deleteGmailDraft(draft.draftId);
  console.log(`✅ Test draft ${draft.draftId} successfully deleted!`);
} catch (err: any) {
  console.error('❌ Live Gmail API call failed:', err.message);
  process.exit(1);
}

console.log('\n🎉 ALL GMAIL DRAFT SERVICE TESTS PASSED!');
